#!/usr/bin/env python3
"""generate_systemd_units.py — translate launchd plists to systemd unit files.

One-time Phase 3 migration tool. Reads `~/Library/LaunchAgents/com.greenwich-barrow.*.plist`
on a Mac that has the plists installed (i.e., the iMac), emits matching `.service` +
`.timer` pairs into `systemd/` at the repo root.

Excludes:
- `com.greenwich-barrow.post-call-analyzer` — WatchPaths-driven, Granola sidecar
  (stays on macOS per `feedback_post_call_analyzer_realtime_on_granola.md`)
- Any plist that uses `WatchPaths` instead of `StartCalendarInterval`/`StartInterval`

Path translation: `/Users/kaycschneider/Documents/AI Operations/` → `%h/projects/Sapling/`
(systemd `%h` expands to the user's home directory at unit-load time).

Usage:
    python3 scripts/generate_systemd_units.py

Re-run after any plist change. Idempotent — overwrites existing files in `systemd/`.
"""

from __future__ import annotations

import plistlib
import sys
from pathlib import Path

LAUNCH_AGENTS = Path.home() / "Library" / "LaunchAgents"
REPO_ROOT = Path(__file__).resolve().parent.parent
SYSTEMD_DIR = REPO_ROOT / "systemd"

EXCLUDE_LABELS = {"com.greenwich-barrow.post-call-analyzer"}
DAY_NAMES = ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"]
MAC_REPO_PREFIX = "/Users/kaycschneider/Documents/AI Operations/"
SERVER_REPO_HOME = "%h/projects/Sapling/"


def translate_schedule(intervals: list[dict]) -> list[str]:
    """Translate StartCalendarInterval entries to systemd OnCalendar lines.

    Strategy: group entries by (Hour, Minute) tuple, collect weekdays per
    group, emit one OnCalendar line per group with the day list. This
    coalesces 5 separate Mon-Fri entries into a single `Mon..Fri 06:00:00`
    line. Falls back to a comma list for non-contiguous days.
    """
    by_time: dict[tuple[int, int], set[int]] = {}
    for entry in intervals:
        h = entry.get("Hour")
        m = entry.get("Minute", 0)
        d = entry.get("Weekday")
        if h is None:
            continue
        key = (int(h), int(m))
        by_time.setdefault(key, set())
        if d is not None:
            by_time[key].add(int(d))

    out = []
    for (h, m), days in sorted(by_time.items()):
        if not days:
            out.append(f"OnCalendar=*-*-* {h:02d}:{m:02d}:00")
            continue
        sorted_days = sorted(days)
        if sorted_days == [1, 2, 3, 4, 5]:
            day_part = "Mon..Fri"
        elif len(sorted_days) == 1:
            day_part = DAY_NAMES[sorted_days[0]]
        elif sorted_days == sorted(range(min(sorted_days), max(sorted_days) + 1)):
            day_part = f"{DAY_NAMES[sorted_days[0]]}..{DAY_NAMES[sorted_days[-1]]}"
        else:
            day_part = ",".join(DAY_NAMES[d] for d in sorted_days)
        out.append(f"OnCalendar={day_part} {h:02d}:{m:02d}:00")
    return out


def path_translate(value: str) -> str:
    return value.replace(MAC_REPO_PREFIX, SERVER_REPO_HOME).replace(
        "$WORKDIR/", SERVER_REPO_HOME
    )


def format_env_line(key: str, value: str) -> str:
    # systemd.exec(5): Environment= splits on whitespace; values with whitespace
    # require the entire KEY=VALUE assignment wrapped in double quotes. Inside
    # those quotes, literal " and \ must be escaped so the env-var value
    # received by the process matches the launchd equivalent verbatim.
    s = str(value)
    if any(c.isspace() for c in s):
        escaped = s.replace("\\", "\\\\").replace('"', '\\"')
        return f'Environment="{key}={escaped}"'
    return f"Environment={key}={s}"


def translate_plist(plist_path: Path) -> tuple[str, str, str] | None:
    with plist_path.open("rb") as f:
        data = plistlib.load(f)

    label = data.get("Label", "")
    if label in EXCLUDE_LABELS:
        return None

    if "WatchPaths" in data:
        return None  # event-driven, not schedulable

    name = label.replace("com.greenwich-barrow.", "")

    intervals = data.get("StartCalendarInterval", [])
    if isinstance(intervals, dict):
        intervals = [intervals]
    start_interval = data.get("StartInterval")

    on_calendar = translate_schedule(intervals) if intervals else []

    if not on_calendar and not start_interval:
        return None

    args = data.get("ProgramArguments", [])
    translated = [path_translate(a) for a in args]
    exec_start = " ".join(translated)

    env = data.get("EnvironmentVariables", {}) or {}

    service_lines = [
        "# Generated by scripts/generate_systemd_units.py — do not edit by hand.",
        f"# Translated from launchd plist: {label}",
        "",
        "[Unit]",
        f"Description=G&B {name}",
        "After=network-online.target",
        "Wants=network-online.target",
        "",
        "[Service]",
        "Type=oneshot",
        f"WorkingDirectory={SERVER_REPO_HOME.rstrip('/')}",
        "Environment=PATH=%h/.npm-global/bin:%h/.local/bin:/usr/local/bin:/usr/bin:/bin",
    ]
    if "LOG_PREFIX" in env:
        service_lines.append(format_env_line("LOG_PREFIX", env["LOG_PREFIX"]))
    if "POST_RUN_CHECK" in env:
        translated_prc = path_translate(env["POST_RUN_CHECK"])
        service_lines.append(format_env_line("POST_RUN_CHECK", translated_prc))
    for k, v in env.items():
        if k in {"HOME", "PATH", "LOG_PREFIX", "POST_RUN_CHECK"}:
            continue
        service_lines.append(format_env_line(k, v))

    service_lines.append(f"ExecStart={exec_start}")
    service_lines.append("")
    service_lines.append("[Install]")
    service_lines.append("WantedBy=default.target")

    timer_lines = [
        "# Generated by scripts/generate_systemd_units.py — do not edit by hand.",
        f"# Translated from launchd plist: {label}",
        "",
        "[Unit]",
        f"Description=G&B {name} timer",
        "",
        "[Timer]",
    ]
    timer_lines.extend(on_calendar)
    if start_interval and not on_calendar:
        timer_lines.append(f"OnUnitActiveSec={int(start_interval)}s")
        timer_lines.append("OnBootSec=2min")
    timer_lines.append("Persistent=true")
    timer_lines.append(f"Unit={name}.service")
    timer_lines.append("")
    timer_lines.append("[Install]")
    timer_lines.append("WantedBy=timers.target")

    return name, "\n".join(service_lines) + "\n", "\n".join(timer_lines) + "\n"


def main() -> int:
    if not LAUNCH_AGENTS.exists():
        print(f"ERROR: {LAUNCH_AGENTS} not found — must run on a Mac with the plists installed", file=sys.stderr)
        return 1

    SYSTEMD_DIR.mkdir(exist_ok=True)
    plists = sorted(LAUNCH_AGENTS.glob("com.greenwich-barrow.*.plist"))
    if not plists:
        print(f"ERROR: no com.greenwich-barrow.*.plist found in {LAUNCH_AGENTS}", file=sys.stderr)
        return 1

    written = []
    skipped = []
    for p in plists:
        try:
            result = translate_plist(p)
        except Exception as exc:
            skipped.append((p.stem.replace("com.greenwich-barrow.", ""), f"error: {exc}"))
            continue
        name = p.stem.replace("com.greenwich-barrow.", "")
        if result is None:
            skipped.append((name, "WatchPaths-driven or no schedule (excluded)"))
            continue
        unit_name, service_body, timer_body = result
        (SYSTEMD_DIR / f"{unit_name}.service").write_text(service_body)
        (SYSTEMD_DIR / f"{unit_name}.timer").write_text(timer_body)
        written.append(unit_name)

    readme = [
        "# Systemd unit templates (Phase 3 Linux migration)",
        "",
        f"Generated 2026-05-07 by `scripts/generate_systemd_units.py`. {len(written)} unit pairs ({len(written) * 2} files).",
        "",
        "Do not edit by hand. To regenerate: re-run the generator script on the iMac (the only host with the source plists).",
        "",
        "## Generated units",
        "",
    ]
    for n in written:
        readme.append(f"- `{n}.service` + `{n}.timer`")
    if skipped:
        readme.append("")
        readme.append("## Excluded plists")
        readme.append("")
        for n, reason in skipped:
            readme.append(f"- `{n}` — {reason}")
    readme.append("")
    readme.append("## Install on server")
    readme.append("")
    readme.append("Run `bash scripts/install_systemd_units.sh` on the server.")
    readme.append("Units are installed but **not enabled** — enable selectively per skill.")
    readme.append("")
    (SYSTEMD_DIR / "README.md").write_text("\n".join(readme) + "\n")

    print(f"wrote {len(written)} unit pairs to {SYSTEMD_DIR}, skipped {len(skipped)}")
    for n in written:
        print(f"  + {n}")
    for n, reason in skipped:
        print(f"  - {n}  ({reason})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
